# Generated by Django 3.2.9 on 2022-01-10 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Couser'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Couser Category'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1. Teacher'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='interested_category',
            new_name='interested',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='moobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='moobile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skill',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
